# Generated by Django 6.0.2 on 2026-02-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspection_raw_prediction_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='is_training_data',
            field=models.BooleanField(default=False, help_text='Marked as High-Value Training Data'),
        ),
    ]
