# Generated by Django 6.0.2 on 2026-02-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_inspection_is_training_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='is_manually_verified',
            field=models.BooleanField(default=False, help_text='Verified by Human Admin'),
        ),
    ]
