# Generated by Django 6.0.2 on 2026-02-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='inspector_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Completed', 'Completed')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='handling_guidelines',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
