# Generated by Django 6.0.2 on 2026-02-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_inventory', '0002_batch_inspector_notes_batch_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='visual_guide',
        ),
        migrations.AddField(
            model_name='batch',
            name='inspector_instructions',
            field=models.TextField(blank=True),
        ),
    ]
